// Two Covers — shared editorial styles (cream paper, brown ink)
export const C = {
  paper: "#FBF6EA", paperDeep: "#F4ECD8", ink: "#3A2C18",
  inkSoft: "#6E5C42", line: "#D8C9A8", accent: "#5C4326",
};
export const serif = "'Fraunces', Georgia, serif";
export const sans = "'Jost', 'Century Gothic', system-ui, sans-serif";

export const S = {
  app: { maxWidth: 480, margin: "0 auto", minHeight: "100vh", background: C.paper,
    color: C.ink, position: "relative", paddingBottom: 84 },

  header: { padding: "22px 24px 16px", textAlign: "center" },
  mastRule: { height: 1, background: C.ink },
  masthead: { fontFamily: serif, fontWeight: 600, fontSize: "clamp(30px, 9vw, 40px)",
    letterSpacing: 4, padding: "8px 0 6px", lineHeight: 1, whiteSpace: "nowrap" },
  initials: { fontFamily: serif, fontStyle: "italic", fontSize: 13, color: C.accent,
    letterSpacing: 1, marginTop: 8 },

  main: { padding: "8px 24px 0" },
  pageTitleRow: { padding: "12px 0 18px", borderBottom: `2px solid ${C.ink}`, marginBottom: 20,
    display: "flex", justifyContent: "space-between", alignItems: "flex-end", gap: 12 },
  pageTitleLeft: { minWidth: 0 },
  pageTitle: { fontFamily: serif, fontStyle: "italic", fontWeight: 500, fontSize: 32,
    margin: 0, lineHeight: 1 },
  lede: { fontFamily: serif, fontSize: 14.5, fontStyle: "italic", color: C.inkSoft,
    lineHeight: 1.5, margin: "0 0 22px" },
  loading: { padding: 60, textAlign: "center", color: C.inkSoft, fontFamily: serif, fontStyle: "italic" },

  card: { width: "100%", display: "block", textAlign: "left", background: "none",
    border: "none", borderBottom: `1px solid ${C.line}`, padding: "14px 0 16px",
    marginBottom: 2, color: C.ink },
  cardTop: { display: "flex", alignItems: "center", gap: 10, marginBottom: 8 },
  cardNo: { fontFamily: serif, fontSize: 12, color: C.inkSoft },
  cardRule: { flex: 1, height: 1, background: C.line },
  cardDate: { fontSize: 9.5, letterSpacing: 1.5, textTransform: "uppercase", color: C.inkSoft },
  cardBody: { display: "flex", alignItems: "center", gap: 14 },
  cardLeft: { flex: 1, minWidth: 0 },
  cardName: { fontFamily: serif, fontSize: 21, fontWeight: 600, lineHeight: 1.15 },
  cardMeta: { fontSize: 11, letterSpacing: 1, textTransform: "uppercase", color: C.inkSoft, marginTop: 5 },

  rankRow: { width: "100%", display: "flex", alignItems: "center", gap: 14, background: "none",
    border: "none", borderBottom: `1px solid ${C.line}`, padding: "16px 0", color: C.ink },
  rankNum: { width: 36, textAlign: "center", fontFamily: serif, fontStyle: "italic",
    fontSize: 20, color: C.accent },

  cityBlock: { marginBottom: 26 },
  cityHead: { display: "flex", justifyContent: "space-between", alignItems: "baseline" },
  cityName: { fontFamily: serif, fontWeight: 600, fontSize: 19 },
  cityAvg: { fontSize: 11, letterSpacing: 1, color: C.inkSoft },
  cityRule: { height: 1, background: C.ink, margin: "8px 0 4px" },
  cityItem: { width: "100%", display: "flex", justifyContent: "space-between", alignItems: "center",
    background: "none", border: "none", borderBottom: `1px solid ${C.line}`,
    padding: "12px 0", color: C.ink },
  cityItemLeft: { display: "flex", alignItems: "baseline", gap: 12, minWidth: 0 },
  cityItemRank: { fontFamily: serif, fontStyle: "italic", fontSize: 15, color: C.accent,
    flexShrink: 0 },
  cityItemName: { fontFamily: serif, fontSize: 16, fontWeight: 500 },

  panel: { borderTop: `1px solid ${C.line}`, padding: "20px 0 8px", marginBottom: 8 },
  panelTitle: { fontFamily: serif, fontStyle: "italic", fontWeight: 500, fontSize: 20,
    margin: "0 0 16px" },

  filterWrap: { display: "flex", flexWrap: "wrap", gap: 7, marginBottom: 18 },
  chip: { background: "none", border: `1px solid ${C.line}`, color: C.inkSoft,
    padding: "6px 12px", fontSize: 10.5, letterSpacing: 1.2,
    textTransform: "uppercase", fontFamily: sans },
  chipActive: { background: C.ink, color: C.paper, borderColor: C.ink },

  rankByRow: { display: "flex", alignItems: "baseline", gap: 8, padding: "9px 0",
    borderBottom: `1px solid ${C.line}` },
  rankByNum: { fontFamily: serif, fontSize: 12, color: C.inkSoft, width: 22 },
  rankByName: { fontFamily: serif, fontSize: 16, fontWeight: 500, flexShrink: 0 },
  rankByDots: { flex: 1, borderBottom: `1px dotted ${C.line}`, margin: "0 2px",
    position: "relative", top: -3 },
  rankByVal: { fontFamily: serif, fontWeight: 600, fontSize: 17 },
  rankByCaption: { fontFamily: serif, fontStyle: "italic", fontSize: 12.5,
    color: C.inkSoft, marginTop: 12 },
  italicInline: { fontStyle: "italic", color: C.accent },

  barRow: { display: "flex", alignItems: "center", gap: 12, marginBottom: 13 },
  barLabel: { width: 72, fontSize: 11, letterSpacing: 1, textTransform: "uppercase", color: C.inkSoft },
  barTrack: { flex: 1, height: 6, background: C.paperDeep, border: `1px solid ${C.line}` },
  barFill: { height: "100%", background: C.accent },
  barVal: { width: 32, textAlign: "right", fontFamily: serif, fontWeight: 600, fontSize: 15 },

  nav: { position: "fixed", bottom: 0, left: "50%", transform: "translateX(-50%)",
    width: "100%", maxWidth: 480, display: "flex", background: C.paper,
    borderTop: `2px solid ${C.ink}` },
  navBtn: { flex: 1, padding: "11px 0 13px", background: "none", border: "none",
    color: C.inkSoft, display: "flex", flexDirection: "column", alignItems: "center",
    gap: 4 },
  navActive: { color: C.ink },
  navLabel: { fontSize: 9, letterSpacing: 1.5, textTransform: "uppercase" },

  fab: { position: "fixed", bottom: 96, right: "max(16px, calc(50% - 240px + 16px))",
    width: 56, height: 56, borderRadius: "50%", background: C.ink, color: C.paper,
    border: `1px solid ${C.paper}`, outline: `1px solid ${C.ink}`,
    display: "flex", alignItems: "center", justifyContent: "center",
    boxShadow: "0 4px 16px rgba(58,44,24,0.35)", zIndex: 40 },

  overlay: { position: "fixed", inset: 0, background: "rgba(58,44,24,0.4)", display: "flex",
    alignItems: "flex-end", justifyContent: "center", zIndex: 50 },
  sheet: { width: "100%", maxWidth: 480, maxHeight: "92vh", background: C.paper,
    display: "flex", flexDirection: "column", borderTop: `2px solid ${C.ink}` },
  sheetHead: { display: "flex", alignItems: "center", justifyContent: "space-between",
    padding: "16px 22px 12px", borderBottom: `1px solid ${C.line}` },
  sheetKicker: { fontSize: 10, letterSpacing: 2.5, textTransform: "uppercase", color: C.inkSoft },
  sheetBody: { padding: "18px 22px", overflowY: "auto", flex: 1 },
  sheetFoot: { padding: "14px 22px", borderTop: `1px solid ${C.line}` },
  iconBtn: { background: "none", border: "none", color: C.ink, padding: 4 },

  field: { display: "block", marginBottom: 14 },
  fieldRow: { display: "flex", gap: 12 },
  fieldLabel: { display: "block", fontFamily: serif, fontStyle: "italic", fontSize: 14,
    marginBottom: 6, color: C.ink },
  input: { width: "100%", boxSizing: "border-box", background: C.paperDeep,
    border: `1px solid ${C.line}`, borderRadius: 0, padding: "10px 12px", color: C.ink,
    fontSize: 14, fontFamily: sans },

  scoreGroup: { borderTop: `1px solid ${C.line}`, padding: "14px 0", marginBottom: 4 },
  scoreGroupHead: { display: "flex", justifyContent: "space-between", alignItems: "baseline" },
  scoreGroupTitle: { fontFamily: serif, fontStyle: "italic", fontWeight: 500, fontSize: 16 },
  scoreGroupTotal: { fontFamily: serif, fontWeight: 600, fontSize: 14, color: C.accent },
  scoreHint: { fontSize: 11, color: C.inkSoft, margin: "4px 0 14px", lineHeight: 1.4 },
  scoreRow: { marginBottom: 14 },
  scoreRowHead: { display: "flex", justifyContent: "space-between", alignItems: "center",
    marginBottom: 6 },
  scoreRowLabel: { fontSize: 11.5, letterSpacing: 1, textTransform: "uppercase", color: C.ink },
  naBtn: { background: "none", border: `1px solid ${C.line}`, color: C.inkSoft,
    fontSize: 9.5, letterSpacing: 1, textTransform: "uppercase", padding: "3px 8px",
    fontFamily: sans },
  naBtnActive: { background: C.accent, color: C.paper, borderColor: C.accent },
  numRow: { display: "flex", flexWrap: "wrap", gap: 4 },
  numBtn: { flex: "1 0 8%", aspectRatio: "1", background: C.paperDeep, border: `1px solid ${C.line}`,
    color: C.ink, fontFamily: serif, fontSize: 13, padding: 0, minWidth: 0 },
  numBtnHalf: { flex: "1 0 8%", background: C.paperDeep, border: `1px solid ${C.line}`,
    color: C.inkSoft, fontFamily: serif, fontSize: 10, padding: "4px 0", minWidth: 0 },
  numBtnActive: { background: C.ink, color: C.paper, borderColor: C.ink, fontWeight: 600 },
  numBtnDim: { opacity: 0.4 },

  saveBtn: { width: "100%", padding: 14, background: C.ink, color: C.paper, border: "none",
    borderRadius: 0, fontFamily: serif, fontStyle: "italic", fontWeight: 500, fontSize: 16,
    letterSpacing: 0.5 },

  detailHead: { textAlign: "center", marginBottom: 18 },
  detailName: { fontFamily: serif, fontWeight: 600, fontSize: 28, margin: 0, lineHeight: 1.1 },
  detailMeta: { fontSize: 10.5, letterSpacing: 1.5, textTransform: "uppercase",
    color: C.inkSoft, margin: "8px 0 0" },
  detailScoreRow: { display: "flex", alignItems: "center", justifyContent: "center", gap: 14 },
  detailScoreCaption: { fontFamily: serif, fontStyle: "italic", fontSize: 13, color: C.inkSoft,
    lineHeight: 1.3 },
  detailRule: { height: 1, background: C.ink, margin: "20px 0" },
  detailScores: { marginBottom: 18 },
  detailCatRow: { display: "flex", alignItems: "baseline", gap: 8,
    padding: "11px 0", borderBottom: `1px solid ${C.line}` },
  detailCatLabel: { fontSize: 11, letterSpacing: 1, textTransform: "uppercase",
    color: C.inkSoft, flexShrink: 0 },
  detailCatDots: { flex: 1, borderBottom: `1px dotted ${C.line}`, position: "relative", top: -3 },
  detailCatVal: { fontFamily: serif, fontWeight: 600, fontSize: 18, flexShrink: 0 },

  notesBox: { fontFamily: serif, fontStyle: "italic", fontSize: 16, lineHeight: 1.55,
    color: C.ink, margin: 0, padding: "4px 0 4px 16px", borderLeft: `2px solid ${C.accent}` },

  confirmBox: { marginTop: 18, padding: "14px 0", borderTop: `1px solid ${C.line}`,
    display: "flex", flexDirection: "column", gap: 10, fontFamily: serif, fontStyle: "italic",
    fontSize: 14 },
  confirmCancel: { flex: 1, padding: 10, background: "none", color: C.ink,
    border: `1px solid ${C.ink}`, fontFamily: sans, fontSize: 12,
    letterSpacing: 1, textTransform: "uppercase" },
  confirmDelete: { flex: 1, padding: 10, background: C.ink, color: C.paper, border: "none",
    fontFamily: sans, fontSize: 12, letterSpacing: 1, textTransform: "uppercase" },

  empty: { padding: "70px 20px", textAlign: "center" },
  emptyMark: { fontFamily: serif, fontSize: 40, color: C.line },
  emptyText: { fontFamily: serif, fontStyle: "italic", fontSize: 15, color: C.inkSoft,
    lineHeight: 1.5, marginTop: 10 },

  errorText: { color: "#A5443A", fontSize: 12.5, marginTop: 8, fontFamily: serif,
    fontStyle: "italic" },

  geoRow: { display: "flex", alignItems: "center", gap: 10, marginBottom: 14,
    marginTop: -4 },
  geoBtn: { flexShrink: 0, background: "none", color: C.ink, border: `1px solid ${C.ink}`,
    padding: "8px 12px", fontFamily: serif, fontStyle: "italic", fontSize: 13 },
  geoStatusText: { fontSize: 11.5, color: C.inkSoft, fontFamily: serif,
    fontStyle: "italic", lineHeight: 1.3 },
  mapWrap: { marginBottom: 22 },

  editRow: { display: "flex", gap: 10, marginBottom: 18 },
  editBtn: { flex: 1, padding: "10px 0", background: "none", color: C.ink,
    border: `1px solid ${C.ink}`, fontFamily: serif, fontStyle: "italic", fontSize: 14 },
};
